CREATE TABLE ProductCategories (
    Id INT IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    CreationDate DATETIME NULL DEFAULT (GETDATE()),
    LastUpdate DATETIME NULL DEFAULT (GETDATE()),
    CONSTRAINT PK_ProductCategories PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE Products (
    Id INT IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    RichTextArea NVARCHAR(MAX) NULL,
    ProductCategoryId INT NOT NULL,
    ImageGuid NVARCHAR(200) NULL,
    CreationDate DATETIME NULL DEFAULT (GETDATE()),
    LastUpdate DATETIME NULL DEFAULT (GETDATE()),
    CONSTRAINT PK_Products PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT FK_Products_ProductCategories FOREIGN KEY (ProductCategoryId) REFERENCES ProductCategories(Id)	ON DELETE CASCADE	ON UPDATE CASCADE
);

 CREATE TABLE AppUsers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
	CreationDate DATETIME NULL DEFAULT (GETDATE()),
	LastUpdate DATETIME NULL DEFAULT (GETDATE()),
);
